module.exports = {
    OVERLAY_ROAD_CONSTRUCTION: false,
    OVERLAY_VALID_POSITIONS: false,
    DEBUGGING: true,
    MIN_HARVESTERS: 4,
    MIN_BUILDERS: 4,
    MIN_FIGHTERS: 0,
    MIN_HEALERS: 0,
    MIN_PRIEST: 0,
    HARVESTER: 'Harvester',
    BUILDER: 'Builder',
    FIGHTER: 'Fighter',
    PRIEST: 'Priest',
    HEALER: 'Healer',
    BODY_CONFIGURATION: {
        HARVESTER: [
            [WORK, WORK, CARRY, MOVE], // RCL 1
            [WORK, WORK, WORK, CARRY, CARRY, MOVE, MOVE, MOVE], // RCL 2
            [WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE], // RCL 3
            [WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, MOVE,MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE], // RCL 4
            [WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, MOVE,MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE], // RCL 4
            [WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, MOVE,MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE], // RCL 4
            [WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, MOVE,MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE], // RCL 4
            [WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, MOVE,MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE], // RCL 4
        ],
        BUILDER: [
            [WORK, WORK, CARRY, MOVE], // RCL 1
            [WORK, WORK, WORK, CARRY, CARRY, MOVE, MOVE, MOVE], // RCL 2
            [WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE], // RCL 3
            [WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, MOVE,MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE], // RCL 4
            [WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, MOVE,MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE], // RCL 4
            [WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, MOVE,MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE], // RCL 4
            [WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, MOVE,MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE], // RCL 4
            [WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, MOVE,MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE], // RCL 4
        ],
        FIGHTER: [
            [TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK, MOVE, MOVE, MOVE, MOVE, MOVE], // RCL 1
            [TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK, MOVE, MOVE, MOVE, MOVE, MOVE], // RCL 1
            [TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK, MOVE, MOVE, MOVE, MOVE, MOVE], // RCL 1
            [TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK, MOVE, MOVE, MOVE, MOVE, MOVE], // RCL 1
            [TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK, MOVE, MOVE, MOVE, MOVE, MOVE], // RCL 1
            [TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK, MOVE, MOVE, MOVE, MOVE, MOVE], // RCL 1
            [TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK, MOVE, MOVE, MOVE, MOVE, MOVE], // RCL 1
            [TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK, MOVE, MOVE, MOVE, MOVE, MOVE], // RCL 1
        ],
        PRIEST: [
            [CLAIM, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, WORK, WORK, WORK, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE], // RCL 1
            [CLAIM, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, WORK, WORK, WORK, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE], // RCL 1
            [CLAIM, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, WORK, WORK, WORK, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE], // RCL 1
            [CLAIM, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, WORK, WORK, WORK, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE], // RCL 1
            [CLAIM, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, WORK, WORK, WORK, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE], // RCL 1
            [CLAIM, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, WORK, WORK, WORK, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE], // RCL 1
            [CLAIM, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, WORK, WORK, WORK, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE], // RCL 1
            [CLAIM, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, WORK, WORK, WORK, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE], // RCL 1
        ],
    },
};



